project_name: wonderful-readme-stats
report_sizes: true

env_files:
  github_token: ~/.github_token

before:
  hooks:
    - go mod download
    - go mod tidy
    - go run golang.org/x/vuln/cmd/govulncheck@latest -test ./...
    - go run github.com/google/osv-scanner/cmd/osv-scanner@latest -r .
    - go run github.com/securego/gosec/v2/cmd/gosec@latest -quiet ./...
    - go run github.com/go-critic/go-critic/cmd/gocritic@latest check -enableAll ./...
    - go run github.com/gordonklaus/ineffassign@latest ./...
    - go test -race ./...

builds:
  -
    id: default
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, windows, darwin ]
    goarch: [ amd64, arm64 ]

upx:
  -
    ids: [ default ]
    enabled: true
    compress: best
    lzma: true
    brute: true
    goos: [ linux, windows ] # skip darwin (latest macOS is not supported now)
    goarch: [ amd64, arm64 ]

release:
  ids: [ default ]
  draft: true
  replace_existing_draft: true
  target_commitish: '{{ .Commit }}'
  prerelease: auto
  mode: replace
  header: |
    ## ✨ The {{ .ProjectName }} `{{ .Tag }}` release
  footer: |
    ## How to update?

    For [Docker][docker_url] users (any platforms):

    ```console
    docker pull koddr/wonderful-readme-stats:latest
    ```

    For other ways (any platforms): manually download and re-install a ready-made package from the `Assets` section.

    > 💡 Note: See the [Complete user guide][project_url] to get a general information.

    ## Your help to improve project

    We would be truly grateful for any help with:

    - Creating tests and benchmarks for code;
    - Improving existing functions, structs, or tests;
    - Feature requests with interesting functions that would be good to add;
    - Say a few words about the project on your social networks and blogs (Dev.to, Medium, Хабр, and so on).

    Your PRs & issues are welcome! Thanks 😉

    <!-- Links -->

    [docker_url]: https://www.docker.com
    [project_url]: https://github.com/koddr/wonderful-readme-stats#-complete-user-guide
  disable: false
  skip_upload: false

dockers:
  -
    id: '{{ .ProjectName }}'
    ids: [ default ]
    image_templates:
      - 'gowebly/{{ .ProjectName }}:latest'
      - 'gowebly/{{ .ProjectName }}:{{ .Tag }}'
      - 'gowebly/{{ .ProjectName }}:v{{ .Major }}'
      - 'gowebly/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .Date }}'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'
      - '--platform=linux/amd64'
    skip_push: false
    push_flags:
      - '--tls-verify=false'

nfpms:
  -
    maintainer: Vic Shóstak <koddr.me@gmail.com>
    description: |
      A wonderful out-of-the-box and self-hosted solution for displaying statistics (stargazers, contributors, etc.) about your repository in your README file.
    homepage: 'https://github.com/koddr/{{ .ProjectName }}'
    license: Apache 2.0
    formats: [ deb, rpm, apk, archlinux ]

archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files: [ LICENSE, README.md ]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  abbrev: -1
  filters:
    exclude: [ '^*.md', '^*.ya?ml' ]
  groups:
    - title: New features
      regexp: ^.*?((A|a)dd)|((F|f)eature).*?$
      order: 0
    - title: Bug fixes
      regexp: ^.*?((B|b)ug)|((F|f)ix).*?$
      order: 1
    - title: Improvements
      regexp: ^.*?(I|i)mprove.*?$
      order: 2
    - title: Updates
      regexp: ^.*?(U|u)pdate.*?$
      order: 3
    - title: Security issues
      regexp: ^.*?(S|s)ecurity.*?$
      order: 4
    - title: Delete unused or stale
      regexp: ^.*?((D|d)elete)|((U|u)nused)|((S|s)tale).*?$
      order: 5
    - title: Others
      order: 999
