# The 'backend' block sets a Go backend options.
# Required to set up.
backend:
  # 'module_name' (string) option can be any name of your Go module (for example, 'github.com/user/project')
  module_name: project
  # 'go_framework' (string) option can be one of the values: 'fiber', 'echo', 'chi', or 'default'
  go_framework: default
  # 'port' (int) option can be any port that is not taken up on your system
  port: 5000

  # The 'timeout' block sets a server options.
  # For more information, see https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
  # Required to set up.
  timeout:
    # 'read' (int) option can be any number of seconds, 5 is recommended
    read: 5
    # 'write' (int) option can be any number of seconds, 10 is recommended
    write: 10

# The 'frontend' block sets a frontend options.
# Required to set up.
frontend:
  # 'package_name' (string) option can be any name of your package.json (for example, 'project')
  package_name: project
  # 'css_framework' (string) option can be one of the values: 'tailwindcss', 'unocss', or 'default'
  css_framework: default
  # 'runtime_environment' (string) option can be one of the values: 'bun', or 'default'
  runtime_environment: default
  # 'htmx' (string) option can be any existing version
  htmx: latest
  # 'hyperscript' (string) option can be any existing version
  hyperscript: latest
